[package]
name = "cbm-dos"
version = "0.1.3"
edition = "2024"
authors = ["Markus Stoller"]
description = "A library to decode and encode gcr bytes (4-to-5)"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/markusstoller/cbm-dos"

[dependencies]
